### PR TITLE
Updates for bionic deb packaging

### PR DESCRIPTION
**Pull request by tmbgreaves**
This PR renames the 'diamond' package to 'spud-diamond' and updates changelog and build deps for bionic.

Addressing issue #8

### CODE REVIEW

**Comment by tmbgreaves** [comment]
Poking a bit more at this, we get an install failure from the package as it depends on python-psyco which isn't available in bionic, and recommends python-rsvg which is also unavailable. I'd be glad of feedback on the preferred way to deal with these two.

**Comment by Patol75** [comment]
I am a bit confused about what you are asking. I cannot find any python-psyco package available for Ubuntu Xenial either, but there is python(3)-psycopg2, which deals with [PostgreSQL](https://www.postgresql.org/). On the other hand, this [webpage](http://psyco.sourceforge.net/) mentions a Psyco package for python that has a JIT compiler. However, the project is dead, and if you are looking for a general Python JIT compiler, you should have a look at [PyPy](https://pypy.org/). There is also [Numba](https://numba.pydata.org/), but it is more Numpy-oriented. Finally, [libRSVG](https://wiki.gnome.org/action/show/Projects/LibRsvg) is available for Python 3 through [PyGObject](https://pygobject.readthedocs.io/en/latest/index.html), with an API Reference [here](https://lazka.github.io/pgi-docs/).

**Comment by stephankramer** [comment]
I think you mean _depends_ on python-rsvg and _recommends_ python-psyco. Yeah I dunno, it seems the rsvg dependency has been added in a single commit without any other changes. There is no `import rsvg` anywhere (the only thing python-rsvg provides is that module). So I'm not sure why that dependency is there. I've remove python-rsvg locally and diamond still seems to function perfectly fine. I thought it might have to do with the logo, but again that seems to still function (in the about dialog for instance).

The python-psyco recommend seems to have been there from the start and again I'm unclear why. So I would suggest just removing both the recommendation and dependency.

I have tried building the debian package with your changes on Debian Buster and it seems to work without any changes, so that's nice.

Only other thing I would suggest, is that we add a `Conflicts:` for `spud-diamond` with the `diamond` binary package. That is both for people that have the older version of our diamond package installed and for people that may have the [other diamond](https://diamond.readthedocs.io/en/latest/) package installed. Both of these include a `/usr/bin/diamond` which is also in `spud-diamond`

**Comment by tmbgreaves** [comment]
Thanks @stephankramer - addressed in 049011

**Pull request merged**
