### PR TITLE
string.count appears to have been deprecated in favor of an oo approach

### PR DESCRIPTION
**Pull request by cianwilson**
A small change to fix spud-update-options

### CODE REVIEW

**Review by angus-g — APPROVED** [review]
`string.count` doesn't exist in Python 3, so LGTM

**Comment by stephankramer** [comment]
Just as an FYI: github isn't talking to Jenkins at the moment due to a certificate issue on our jenkins server that I believe @tmbgreaves  is looking into. That's why the tests aren't running

**Comment by cianwilson** [comment]
Thanks @angus-g and @stephankramer.  I'll wait until the Jenkins issues are sorted to merge just in case there's some test case that depends on this in an unexpected way.

**Comment by tmbgreaves** [comment]
This is being annoyingly awkward to resolve - sorry for the delay. I thought I'd put a new and correct cert chain in place but whilst some validators accept it, others seem to dislike it. I have an open support ticket with our certificate issuer (Imperial ICT) asking them to take a look and probably give us a completely new certificate in an attempt to properly fix the bug.

FWIW the background problem is as described at: https://www.auscert.org.au/blog/2021-01-15-quovadis-issue-impacting-multiple-customers

**Comment by tmbgreaves** [comment]
Jenkins should *hopefully* be working OK now. Very annoying bug, now I think resolved or at least worked around. Do let me know if you see more problems...

**Comment by stephankramer** [comment]
@tmbgreaves : that's good news! Any idea whether we now need to re-issue the PR? I tried a commit to force an update on this PR, but it seems Jenkins is still not aware that this PR even exists. Let me try open and closing...

**Comment by stephankramer** [comment]
Let's see what happens

**Comment by stephankramer** [comment]
No that didn't work. Closing again and reopening as a new PR

**Pull request closed without merging**
