### PR TITLE
Add basic python 3.X support.

### PR DESCRIPTION
**Pull request by jrper**
This changeset makes the minimum list of modifications needed so that the python libspud.so library can be built with python versions 3.X. Note that this doesn't introduce any proper sanitisation on unicode input, and assumes that it's safe to shadow PyInt_Type with PyLong_Type. Both assumptions can fail messily.

### CODE REVIEW

**Comment by jrper** [comment]
Added one more change so that libspud builds on systems where python points to python3.

**Comment by jrper** [comment]
@stephankramer @cianwilson Is there any chance of either of you taking a look at this? The easiest way to test is probably to build under a python3 virtual environment. Since there doesn't appear to be a direct spud testing structure, the basics will get exercised downstream in Fluidity.

**Comment by drhodrid** [comment]
Just to check - is this now superfluous given the recent merge of #7 ?

**Comment by cianwilson** [comment]
I believe so, yes @drhodrid . It seems the diff and commit SHAs were a little misleading here but all those changes should be in now so closing.  Feel free to reopen if I'm wrong.

**Pull request closed without merging**
