### PR TITLE
Update config.guess with the most recent version.

### PR DESCRIPTION
**Pull request by cianwilson**
The new version comes from:
http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD

This is necessary to allow configure to work out the arm64 architecture.

### CODE REVIEW

**Comment by angus-g** [comment]
Is it possible that `config.sub` should be updated too (http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD)?

**Comment by cianwilson** [comment]
Happy to do that but it wasn't necessary when I tried the different OS's I
have access to so I didn't include it. Did you come across a system where
it was needed that I should try?

**Comment by angus-g** [comment]
I haven't, I just noticed that there were also some references to `arm64` there as well. Maybe it's good practice to keep `.guess` and `.sub` in sync, but I have no idea! If it works with `.guess` alone, it's probably fine?

**Comment by cianwilson** [comment]
Good point.  I don't know enough about these files to know what level of consistency is required but I've just pushed a version with the latest `config.sub` (slightly different timestamp to the `config.guess`) to see if the tester is happy with it.

**Review by angus-g — APPROVED** [review]
Looks like CI is happy, I don't see why this couldn't go in!

**Comment by cianwilson** [comment]
Thanks! Appears to be happy on my `arm64` machine too so I went ahead and merged.

**Pull request merged**
