### PR TITLE
Python3 packaging

### PR DESCRIPTION
**Pull request by stephankramer**
Previously diamond and spud had been made python3 compatible. But in a
systems that keep python -> python2 (which will be all Debian/Ubuntu systems
for the near future), this doesn't actually switch over to python3 (unless you corrupt your system).

Changes:
- change all #!/usr/bin/env to python3 instead of python
- remove unnecessary #!/usr/bin/env/python in python files that function
as a module only
- change dependencies in debian package to remove any depency on python
(which pulls in python2)
- also fix the gtk dependencies (we switched over to using python-gi
instead of python-gtk2 but this had never been updated in the control
files and the documentation)
- rename python-dxdiff and python-spud packages to python3-dxdiff and
python3-spud
- remove config.guess and config.sub
- remove hideous search and replace of #!s (to be discussed)
- in the Jenkins file only test for python3, as I don't think there is much worth in maintaining python2 compatibility
- change the dockerfile to a python3 environment

### CODE REVIEW

**Comment by stephankramer** [comment]
So this brings up again the point about what to with the #! in diamond. Here I have a little more sympathy for the argument that it is a little awkward that diamond break as soon as you switch to a different python environment.
In the case of fluidity tools, I would say that if you want to use them in a different python environment then just rebuild them in that environment (unless I'm overlooking something) - in the case of diamond, that is all a little more awkward: people don't typically use the "system installed" diamond, even if you use a local diamond you still need to set python paths etc.
So I'd like hear people's (in particular @cianwilson  and @jrper 's opinion). In master diamond has `#!/usr/bin/python` on top which I guess we could replace with `#!/usr/bin/python3` ? Is that however an appropriate thing to do at the Debian/Ubuntu packaging level (there's some hideous sed stuff in debian/rules that I've taken out for the moment in this branch), or should it be integrated with `make install`. I think hard-coding from the start is not really an option, as people might be "building" with a python3 in a different location, /usr/local/bin/ or some python environment...

**Comment by cianwilson** [comment]
Hi @stephankramer,

Thanks for this.  The updates to the debian build system are clearly needed and were overlooked in the "upgrade."

Can I just check what this does to python2 compatibility?  I think we were quite careful with the python3 upgrade to allow it to still work with python2 and I generally test this using virtualenvs and local builds.  Is the plan here to drop this?  Not necessarily opposed to this, just checking.

Cheers,
Cian

**Comment by stephankramer** [comment]
Good question. This depends a bit on what we do with the shebangs. So currently diamond has `#!/usr/bin/env python` but in the Debian/Ubuntu package it ends up with (due to some sed-hack in debian/rules as `#!/usr/bin/python`. Both forms have the issue that system `python` will keep pointing to python2 for the foreseeable future in Debian/Ubuntu (and some other distros). A bare install with only python3 might not even have `/usr/bin/python`. So in this branch I changed it to `#!/usr/bin/env python3` which is the standard thing to do for python3 packages.

However, if you would use this for the packaged version it means that as soon as you switch to a different python environment the "system diamond" will break as it will not have the diamond python modules available. So discussing this with @jrper ,  I thought the best thing to do would be to replace the she- bang line during "make install" with the full-path to the `python3` that has been picked up by configure. So if you configure with `/usr/bin/python3` in the path, it changes it to `#!/usr/bin/python3`. If you configure it with some python venv active it will hard-code the path to its `python3` into the she-bang.

In principle we could have a configure option for it to instead use the `python` that's in the path, or the python2 or whatever. I don't think it would be correct to *default* to `python` in the path, as again that would mean that on Debian and Ubuntu systems you would default to python2 (on these distros /usr/bin/python is not seen as the default python, but the default python2, python3 is a different language).

**Comment by stephankramer** [comment]
OK, I was wrong. Apparently distutils takes care of this for us (replacing the she-bang with a hardcoded python binary path). So since we install everything via `setup.py` this all works correctly already (in the branch).

Coming back to your question @cianwilson : if we want to maintain python2 functionality (in python2 environments, etc.) - we need a way to tell the install targets in the main Makefile to use `python` instead of `python3`. Before I do, just wanted to check - do we care enough? I'm also happy to drop python2 support altogether...

**Comment by stephankramer** [comment]
@tmbgreaves : I've just pushed an update to this PR but it seems Jenkins is not picking it up. Am I being impatient?

**Comment by tmbgreaves** [comment]
Thanks for the heads-up, @stephankramer  - I'll take a look.

**Comment by tmbgreaves** [comment]
Jenkins problems fixed, I think - broken access token.

**Comment by stephankramer** [comment]
@cianwilson: I have reinstated the libspud tests with python2. Is there anything more you would like to be tested with python2 (see Jenkinsfile). I'm inclined not to support python2 in "configure+make install" as it is a bit of faff, but let me know if you want it. It'd be good to get this merged, as it holds up a similar thing for fluidity (https://github.com/FluidityProject/fluidity/pull/238) which holds up a number of other PRs.

**Comment by stephankramer** [comment]
Have merged this now to keep things going. @cianwilson: if there's anything further you'd like me to do on this, please let me know

**Pull request merged**
